
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ramiz
 */
public class EditDoctor extends javax.swing.JFrame {

    int doktorID;
    DoctorList doktorlist;

    public EditDoctor(int doktorID, DoctorList doktorList) throws SQLException {
        initComponents();
        this.doktorID = doktorID;
        this.doktorlist = doktorList;
        String query = "select * from doktor where doktor_id=?";
        PreparedStatement stat;
        ResultSet rs;
        //Doktor bilgileri alınıyor
        stat = MainScreen.conn.prepareStatement(query);
        stat.setInt(1, doktorID);
        rs = stat.executeQuery();
        rs.next();
        //Doktor bilgileri gerekli bloklara yerleştiriliyor
        NameText1.setText(rs.getString(2));
        SurnameText1.setText(rs.getString(3));

        //uzmanlik listeye ve combobox a ekleniyor
        query = "select * from uzmanlik order by uzmanlik_id";
        stat = MainScreen.conn.prepareStatement(query);
        rs = stat.executeQuery();
        while (rs.next()) {
            UzmanlikCombo1.addItem(rs.getInt(1) + " - " + rs.getString(2));
        }

        query = "select * from hastane order by hastane_id";
        stat = MainScreen.conn.prepareStatement(query);
        rs = stat.executeQuery();
        while (rs.next()) {
            HastaneCombo1.addItem(rs.getInt(1) + " - " + rs.getString(2));
        }
        stat.close();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
     * Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameText = new javax.swing.JTextField();
        SurnameText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        UzmanlikCombo = new javax.swing.JComboBox<>();
        discard = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        HastaneCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NameText1 = new javax.swing.JTextField();
        SurnameText1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        UzmanlikCombo1 = new javax.swing.JComboBox<>();
        discard1 = new javax.swing.JButton();
        save1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        HastaneCombo1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        NameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextActionPerformed(evt);
            }
        });

        jLabel4.setText("Uzmanlık Alanı:");

        UzmanlikCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UzmanlikComboActionPerformed(evt);
            }
        });

        discard.setText("İptal");
        discard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardActionPerformed(evt);
            }
        });

        save.setText("Kaydet");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel3.setText("Hastane:");

        HastaneCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HastaneComboActionPerformed(evt);
            }
        });

        jLabel1.setText("Ad:");

        jLabel2.setText("Soyad:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Doktor Düzenle");

        NameText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameText1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Uzmanlık Alanı:");

        UzmanlikCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UzmanlikCombo1ActionPerformed(evt);
            }
        });

        discard1.setText("İptal");
        discard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discard1ActionPerformed(evt);
            }
        });

        save1.setText("Kaydet");
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Hastane:");

        HastaneCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HastaneCombo1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Ad:");

        jLabel8.setText("Soyad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SurnameText1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                            .addComponent(NameText1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(discard1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                        .addComponent(save1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UzmanlikCombo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HastaneCombo1, 0, 363, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(NameText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(SurnameText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(UzmanlikCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(HastaneCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discard1)
                    .addComponent(save1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextActionPerformed

    private void UzmanlikComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UzmanlikComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UzmanlikComboActionPerformed

    private void discardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardActionPerformed
        this.dispose();
    }//GEN-LAST:event_discardActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String query = "INSERT INTO doktor(ad, soyad, doktor_uzm, doktor_hast) VALUES (?, ?, ?, ?);";
        try {
            PreparedStatement stat = MainScreen.conn.prepareStatement(query);
            stat.setString(1, NameText.getText());
            stat.setString(2, SurnameText.getText());
            stat.setInt(3, Integer.parseInt(UzmanlikCombo.getSelectedItem().toString().split(" - ")[0]));
            stat.setInt(4, Integer.parseInt(HastaneCombo.getSelectedItem().toString().split(" - ")[0]));
            stat.execute();
            doktorlist.updateDoktorTablosu();
            stat.close();
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(EditDoctor.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            this.dispose();
        }
    }//GEN-LAST:event_saveActionPerformed

    private void HastaneComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HastaneComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HastaneComboActionPerformed

    private void NameText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameText1ActionPerformed

    private void UzmanlikCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UzmanlikCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UzmanlikCombo1ActionPerformed

    private void discard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discard1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_discard1ActionPerformed

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed
        String query = "update doktor set ad=?,soyad=?, doktor_uzm=?, doktor_hast=? where doktor_id=?";
        try {
            PreparedStatement stat = MainScreen.conn.prepareStatement(query);
            stat.setString(1, NameText1.getText());
            stat.setString(2, SurnameText1.getText());
            stat.setInt(3, Integer.parseInt(UzmanlikCombo1.getSelectedItem().toString().split(" - ")[0]));
            stat.setInt(4, Integer.parseInt(HastaneCombo1.getSelectedItem().toString().split(" - ")[0]));
            stat.setInt(5, doktorID);
            stat.execute();
            doktorlist.updateDoktorTablosu();
            stat.close();
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(EditDoctor.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            this.dispose();
        }
    }//GEN-LAST:event_save1ActionPerformed

    private void HastaneCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HastaneCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HastaneCombo1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> HastaneCombo;
    private javax.swing.JComboBox<String> HastaneCombo1;
    private javax.swing.JTextField NameText;
    private javax.swing.JTextField NameText1;
    private javax.swing.JTextField SurnameText;
    private javax.swing.JTextField SurnameText1;
    private javax.swing.JComboBox<String> UzmanlikCombo;
    private javax.swing.JComboBox<String> UzmanlikCombo1;
    private javax.swing.JButton discard;
    private javax.swing.JButton discard1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton save;
    private javax.swing.JButton save1;
    // End of variables declaration//GEN-END:variables
}
